---
- name: Generate NX-OS Configuration Files
  hosts: nxos
  tasks:
    - name: Generate NX-OS Configuration Files
      template:
        src: templates/nxos-interfaces-macro.j2
        dest: "./configs/{{ inventory_hostname }}-interfaces.txt"
