---
- name: Generate BGP + VRF Configurations
  hosts: nxos
  tasks:
    - name: Generate BGP + VRF Configs
      template:
        src: nxos-base.j2
        dest: "./configs/{{ inventory_hostname }}-interfaces.txt"
