---
creds_ssh:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: cli
creds_nxapi:
  host: "{{ ansible_host }}"
  username: "{{ username }}"
  password: "{{ password }}"
  transport: nxapi
  use_ssl: yes
  validate_certs: no
  port: 8443
  
name_server1: 8.8.8.8
name_server2: 8.8.4.4
default_domain: bogus1.com
ntp1: 130.126.24.24
ntp2: 152.2.21.1
  
global_config:
  - "ip domain-name {{ default_domain }}"
  - "ip name-server {{ name_server1 }} {{ name_server2 }}"
  - "ntp server {{ ntp1 }}"
  - "ntp server {{ ntp2 }}"
