---
- name: Gather IOS Facts
  hosts: cisco
  vars:
    cli:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - ios_facts:
        provider: "{{ cli }}"
      tags: facts
    - debug: 
        msg: "{{ ansible_net_serialnum }}"
