---
- name: 3 - Show ARP

  hosts: cisco

  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"

  tasks:

    - name: run multiple commands and evaluate the output
      ios_command:
        commands:
         -  show arp
        provider: "{{ creds }}"
      register: show_arp

    - debug:
        msg: "{{ show_arp }}"

    - set_fact: 
        show_arp_new: "{{ show_arp.stdout_lines[0] }}"

    - debug:
        msg: "{{ show_arp_new }}"

    - debug:
        msg: "{{ item }}"
      with_items: "{{ show_arp_new }}"
      when: "'10.220.88.1' in item"
