---

    ssh:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: cli
      timeout: 30

    nxapi:
      host: "{{ ansible_host }}" 
      username: "{{ username }}" 
      password: "{{ password }}" 
      transport: nxapi
      use_ssl: yes
      validate_certs: no
      port: 8443
      timeout: 30
