---
- name: NXOS Ping

  hosts: nxos

  tasks:
    - name: Ping
      nxos_ping:
        dest: 10.10.10.2 
        provider: "{{ ssh }}"  
      register: ping

    - debug:
        msg: "{{ ping }}"

    - debug: 
        msg: "Ping Successful"
      when: (ping.packet_loss == "0.00%")
