---
- name: NAPALM Install Config


  hosts: nxos

  tasks:
  - name: Install Config
    napalm_install_config:
      provider: "{{ creds }}"
      config_file: "./configs/{{ inventory_hostname }}.txt"
      diff_file: "./diffs/{{ inventory_hostname }}.txt"
      commit_changes: True
      replace_config: False

  - name: napalm_get_facts
    napalm_get_facts:
      provider: "{{ creds }}"
      filter: 'interfaces_ip'

  - set_fact:
      device_ip: "{{ napalm_interfaces_ip['Ethernet2/1']['ipv4'] }}"

  - set_fact:
      device_ip: "{{ item }}"
    with_items: "{{ device_ip }}"

  - assert:
      that: device_ip in ["10.1.1.1", "10.1.1.2"]
